eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
        - id: product
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/product/**
        - id: restaurant
          uri: http://localhost:9020
          predicates:
            - Path=/api/v1/restaurant/**

